### PR TITLE
add icon for repo

### LINKED ISSUE #58: plugin icon is missing
To show an icon for the plugin in the repo, there needs to be at least one image file be placed inside the `pix` folder.
Details see: https://moodledev.io/docs/4.2/apis/commonfiles#pixiconsvg

### PR DESCRIPTION
**Pull request by individual-it**
fixes #58

### CODE REVIEW

**Comment by PhMemmel** [comment]
Is it possible to use a svg icon?

**Comment by individual-it** [comment]
Yes, need to find one official

**Comment by koebel** [comment]
Here you go: https://owncloud.com/trademark/

oc-logo-1c-RGB
oc-logo-1c-slogan-RGB
oc-logo-2c-slogan-transparent-RGB

**Comment by individual-it** [comment]
there seems not to be any official .svg image that looks good enough on the correct size (16x16)
I've uploaded the official small png file. I think this is good to go now.
Any user can overwrite the icon anyway in the template.

**Review by S-Panta — APPROVED** [review]

**Pull request merged**
